---
# tasks file for helm
- name: Helm GPG-key (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  block:
    - name: Install apt-transport-https
      become: true
      ansible.builtin.package:
        name: apt-transport-https
        state: present
      register: packages_install_result
      until: packages_install_result is success
      retries: 30
      delay: 20

    - name: Create /etc/apt/keyrings directory
      become: true
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Get Helm GPG-key
      become: true
      ansible.builtin.get_url:
        url: "{{ helm_deb_gpg_key_url }}"
        dest: /tmp/helm-gpgkey
        mode: '0644'

    - name: Create binary Helm GPG-key
      become: true
      ansible.builtin.command:
        cmd: gpg --dearmor -o /etc/apt/keyrings/helm.gpg /tmp/helm-gpgkey
        creates: /etc/apt/keyrings/helm.gpg

    - name: Add Helm repository
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/helm.gpg] {{ helm_deb_repo_url }}"
        filename: helm-stable-debian
        state: present
        update_cache: true

- name: Install Helm
  become: true
  ansible.builtin.package:
    name: helm
    state: present
  register: helm_install_result
  until: helm_install_result is success
  retries: 30
  delay: 20
