---
- name: Check hosts availability
  hosts: all
  gather_facts: false
  tasks:
    - name: Check SSH availability
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300

    - name: Gather facts
      ansible.builtin.setup:

- name: Prepare K8s-nodes
  hosts: k8s_master,k8s_worker
  roles:
    - k8s_nodes

    - role: k8s_master
      when: "'k8s_master' in group_names"

    - role: calico
      when: "'k8s_master' in group_names"

    - role: k8s_worker
      when: "'k8s_worker' in group_names"

    - role: ingress_nginx
      when: "'k8s_master' in group_names"

    - role: kube_prometheus
      when: "'k8s_master' in group_names"

# - name: Deploy K8s master
#   hosts: k8s_master
#   roles:
#     - k8s_master
#     - calico

# - name: Deploy K8s worker
#   hosts: k8s_worker
#   roles:
#     - k8s_worker

# - name: Deploy ingress-nginx controller
#   hosts: k8s_master
#   roles:
#     - ingress_nginx
#     - kube_prometheus
