---
- name: Check hosts availability
  hosts: k8s_master
  gather_facts: false
  tasks:
    - name: Check SSH availability
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 300

    - name: Gather facts
      ansible.builtin.setup:

- name: Create secret for deployment
  hosts: k8s_master
  roles:
    - ycr_secret
