---
# tasks file for gha_arc
- name: Install GitHub ARC
  when: ansible_host == apiserver_advertise_address
  block:
    - name: Check Kubernetes API
      kubernetes.core.k8s_info:
        kind: Node
      register: node_list
      until:
        - node_list.resources is defined
        - node_list.resources | length > 0
      retries: 10
      delay: 10
      ignore_errors: false

    - name: Create namespaces
      kubernetes.core.k8s:
        name: "{{ item }}"
        kind: Namespace
        state: present
      loop:
        - "{{ gha_arc_namespace }}"
        - "{{ gha_runners_namespace }}"
        - "{{ app_namespace }}"

    - name: Create secret for GitHub App
      no_log: true
      diff: false
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ gha_arc_secret_name }}"
            namespace: "{{ gha_runners_namespace }}"
          stringData:
            github_app_id: "{{ github_app_id }}"
            github_app_installation_id: "{{ github_app_installation_id }}"
            github_app_private_key: "{{ github_app_private_key }}"

    - name: Install ARC controller
      kubernetes.core.helm:
        name: gha-arc-controller
        chart_ref: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
        release_namespace: "{{ gha_arc_namespace }}"
        wait: true

    - name: Install runner scale set
      kubernetes.core.helm:
        name: "{{ gha_runner_set_name }}"
        chart_ref: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
        release_namespace: "{{ gha_runners_namespace }}"
        values:
          githubConfigUrl: "{{ github_config_url }}"
          githubConfigSecret: "{{ gha_arc_secret_name }}"
          minRunners: 1
          maxRunners: 5
          containerMode:
            type: dind
          controllerServiceAccount:
            name: "{{ gha_arc_sa_name }}"
            namespace: "{{ gha_arc_namespace }}"
          # template:
          #   spec:
          #     serviceAccountName: "{{ gha_arc_sa_name }}"
          #     containers:
          #       - name: runner
          #         image: ghcr.io/actions/actions-runner-controller-charts/actions-runner:latest
          #         command: ["/home/runner/run.sh"]
          #         env:
          #           - name: DOCKER_HOST
          #             value: tcp://localhost:2375
          #       - name: dind
          #         image: docker:dind
          #         securityContext:
          #           privileged: true
          #         env:
          #           - name: DOCKER_TLS_CERTDIR
          #             value: ""
        wait: true

    # Права на управление эфемерными подами в namespace gha-arc-runners
    - name: Create role for ARC management
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: Role
          metadata:
            name: "{{ gha_arc_mgmt_role_name }}"
            namespace: "{{ gha_runners_namespace }}"
          rules:
            - apiGroups: [""]
              resources: ["pods", "pods/exec", "pods/log", "pods/status"]
              verbs: ["get", "list", "watch", "create", "delete", "patch"]
            - apiGroups: ["batch"]
              resources: ["jobs"]
              verbs: ["get", "list", "watch", "create", "delete", "patch"]
            - apiGroups: [""]
              resources: ["secrets"]
              verbs: ["get", "list", "watch"]

    - name: Bind management role to ARC ServiceAccount
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: arc-runner-manager-binding
            namespace: "{{ gha_runners_namespace }}"
          subjects:
            - kind: ServiceAccount
              name: "{{ gha_arc_sa_name }}"
              # namespace: "{{ gha_runners_namespace }}"
              namespace: "{{ gha_arc_namespace }}"
          roleRef:
            kind: Role
            name: "{{ gha_arc_mgmt_role_name }}"
            apiGroup: rbac.authorization.k8s.io

    # Права для деплоя через Helm в namespace app
    - name: Create role for app deployment via Helm
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: Role
          metadata:
            name: "{{ gha_arc_deploer_role_name }}"
            namespace: "{{ app_namespace }}"
          rules:
            - apiGroups: ["", "apps", "batch", "extensions", "networking.k8s.io"]
              resources: ["*"]
              verbs: ["*"]

    - name: Bind deploer role to ARC ServiceAccount
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: gha-arc-runner-rb
            namespace: "{{ app_namespace }}"
          subjects:
            - kind: ServiceAccount
              name: "{{ gha_arc_sa_name }}"
              namespace: "{{ gha_runners_namespace }}"
          roleRef:
            kind: Role
            name: "{{ gha_arc_deploer_role_name }}"
            apiGroup: rbac.authorization.k8s.io
