---
# tasks file for ycr_secret
- name: Create secret
  when: ansible_host == apiserver_advertise_address
  block:
    - name: Check Kubernetes API
      kubernetes.core.k8s_info:
        kind: Node
      register: node_list
      until:
        - node_list.resources is defined
        - node_list.resources | length > 0
      retries: 10
      delay: 10
      ignore_errors: false

    - name: Create imagePullSecret
      no_log: true
      diff: false
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: ycr-secret
            namespace: "{{ app_namespace }}"
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: >-
              {{
                {
                  "auths": {
                    "cr.yandex": {
                      "auth": ("json_key:" + lookup('file', sa_key_file_path)) | b64encode
                    }
                  }
                } | to_json
              }}
