---
# tasks file for ingress-nginx
- name: Ingress-nginx controller
  when: ansible_host == ingress_nginx_apiserver_advertise_address
  block:
    - name: Get k8s node list
      kubernetes.core.k8s_info:
        kind: Node
      register: ingress_nginx_node_list

    - name: Check worker-nodes available
      ansible.builtin.assert:
        that:
          - (
              ingress_nginx_node_list.resources |
              selectattr('metadata.labels', 'defined') |
              rejectattr('metadata.labels["node-role.kubernetes.io/control-plane"]', 'defined') |
              rejectattr('metadata.labels["node-role.kubernetes.io/master"]', 'defined') |
              list | length > 0
            )
        fail_msg: "No worker-nodes found. Please start the k8s_worker role first."
        success_msg: "Worker-nodes found"

    - name: Install ingress-nginx controller
      when: (
              ingress_nginx_node_list.resources |
              selectattr('metadata.labels', 'defined') |
              rejectattr('metadata.labels["node-role.kubernetes.io/control-plane"]', 'defined') |
              rejectattr('metadata.labels["node-role.kubernetes.io/master"]', 'defined') |
              list | length > 0
            )
      block:
        - name: Add ingress-nginx repository
          kubernetes.core.helm_repository:
            name: ingress-nginx
            repo_url: "https://kubernetes.github.io/ingress-nginx"

        - name: Install ingress-nginx
          kubernetes.core.helm:
            name: ingress-nginx
            chart_ref: ingress-nginx/ingress-nginx
            release_namespace: ingress-nginx
            create_namespace: true
            wait: true
            values:
              controller:
                kind: DaemonSet
                service:
                  type: NodePort
                  nodePorts:
                    http: "{{ ingress_nginx_http_node_port }}"
                ingressClassResource:
                  name: nginx
                  enabled: true
                  default: true
