---
# tasks file for argocd
- name: Install GitHub ARC
  when: ansible_host == apiserver_advertise_address
  block:
    - name: Check Kubernetes API
      kubernetes.core.k8s_info:
        kind: Node
      register: node_list
      until:
        - node_list.resources is defined
        - node_list.resources | length > 0
      retries: 10
      delay: 10
      ignore_errors: false

    - name: Create namespaces
      kubernetes.core.k8s:
        name: "{{ item }}"
        kind: Namespace
        state: present
      loop:
        - "{{ argocd_namespace }}"
        - "{{ app_namespace }}"

    - name: Install ArgoCD
      kubernetes.core.k8s:
        state: present
        src: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
        namespace: "{{ argocd_namespace }}"
        apply: true
        server_side_apply:
          field_manager: ansible
          force_conflicts: true

    - name: Install Python packages on control node
      delegate_to: localhost
      connection: local
      ansible.builtin.command:
        cmd: "{{ ansible_playbook_python }} -m pip install passlib bcrypt==4.0.1 kubernetes"
      register: pip_install_result
      changed_when: "'Successfully installed' in pip_install_result.stdout"

    # требуется установка bcrypt на управляющем хосте Ansible
    - name: Set administrative password
      no_log: true
      diff: false
      kubernetes.core.k8s:
        state: patched
        kind: Secret
        name: argocd-secret
        namespace: "{{ argocd_namespace }}"
        definition:
          data:
            admin.password: "{{ argocd_admin_password | password_hash('bcrypt') | b64encode }}"
            admin.passwordMtime: "{{ ansible_date_time.iso8601 | b64encode }}"

    - name: Delete temp password ArgoCD
      kubernetes.core.k8s:
        state: absent
        kind: Secret
        name: argocd-initial-admin-secret
        namespace: "{{ argocd_namespace }}"

    - name: Create ImagePullSecret for Yandex Registry
      no_log: true
      diff: false
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Secret
          metadata:
            name: ycr-secret
            namespace: "{{ app_namespace }}"
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: >-
              {{
                {
                  "auths": {
                    "cr.yandex": {
                      "auth": ("json_key:" + lookup('file', sa_key_file_path)) | b64encode
                    }
                  }
                } | to_json | b64encode
              }}

    - name: Create Application to connect with GitHub
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: "{{ app_name }}"
            namespace: "{{ argocd_namespace }}"
          spec:
            project: default
            source:
              repoURL: "{{ github_repo_url }}"
              targetRevision: main
              path: "{{ guthub_target }}"
              helm:
                valueFiles: ["values.yaml"]
            destination:
              server: https://kubernetes.default.svc
              namespace: "{{ app_namespace }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true

    # - name: Configure ArgoCD ConfigMap for path-based routing
    #   kubernetes.core.k8s:
    #     state: present
    #     definition:
    #       kind: ConfigMap
    #       metadata:
    #         name: argocd-cmd-params-cm
    #         namespace: "{{ argocd_namespace }}"
    #         labels:
    #           app.kubernetes.io/name: argocd-cmd-params-cm
    #           app.kubernetes.io/part-of: argocd
    #       data:
    #         # server.insecure: "true"
    #         server.basehref: "/argocd"
    #         server.rootpath: "/argocd"

    # - name: Create ArgoCD Ingress rule
    #   kubernetes.core.k8s:
    #     state: present
    #     definition:
    #       apiVersion: networking.k8s.io/v1
    #       kind: Ingress
    #       metadata:
    #         name: argocd-server-ingress
    #         namespace: "{{ argocd_namespace }}"
    #         annotations:
    #           nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"   # Обязательно: ArgoCD внутри пода использует HTTPS
    #           nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"     # Отключаем проверку сертификата между Nginx и подом ArgoCD
    #           nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    #           # nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    #           # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #           # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    #           # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    #       spec:
    #         ingressClassName: nginx
    #         rules:
    #           - http:
    #               paths:
    #                 - path: /argocd
    #                   pathType: Prefix
    #                   backend:
    #                     service:
    #                       name: argocd-server
    #                       port:
    #                         number: 443
    #                         # name: https

    - name: Configure ArgoCD ConfigMap for path-based routing
      kubernetes.core.k8s:
        state: patched
        kind: ConfigMap
        name: argocd-cmd-params-cm
        namespace: "{{ argocd_namespace }}"
        definition:
          data:
            server.basehref: "/argocd"
            server.rootpath: "/argocd"
            # server.insecure: "true"

    - name: Restart argocd-server
      kubernetes.core.k8s:
        state: patched
        kind: Deployment
        name: argocd-server
        namespace: "{{ argocd_namespace }}"
        definition:
          spec:
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/restartedAt: "{{ ansible_date_time.iso8601 }}"

    - name: Create ArgoCD Ingress rule
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: argocd-server-ingress
            namespace: "{{ argocd_namespace }}"
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
              nginx.ingress.kubernetes.io/x-forwarded-prefix: "/argocd"
          spec:
            rules:
              - http:
                  paths:
                    - path: /argocd
                      pathType: Prefix
                      backend:
                        service:
                          name: argocd-server
                          port:
                            number: 443
