---
# tasks file for k8s_worker
- name: Check Kubernetes cluster initialization
  become: true
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: k8s_worker_check_init_kubeadm

- name: Check join command
  ansible.builtin.assert:
    that: "'K8s_data' in hostvars"
    fail_msg: "No join command found. Please start the k8s_master role first."
    success_msg: "Join command found"

- name: Join worker-node to Kubernetes cluster
  no_log: true
  diff: false
  become: true
  ansible.builtin.command: "{{ hostvars['K8s_data']['join_worker_cmd'] }}"
  when: not k8s_worker_check_init_kubeadm.stat.exists
  register: k8s_worker_kubeadm_join_result
  changed_when: "'node has joined the cluster' in k8s_worker_kubeadm_join_result.stdout"
