---
# tasks file for k8s_worker
- name: Check init Kubernetes cluster
  become: true
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: check_init_kubeadm

- name: Check join command exist
  ansible.builtin.assert:
    that: "'K8s_data' in hostvars"
    fail_msg: "No join command found. Please start the k8s_master role first."
    success_msg: "Join command found"

- name: Join Kubernetes cluster worker
  become: true
  ansible.builtin.shell: "{{ hostvars['K8s_data']['join_worker_cmd'] }}"
  when: not check_init_kubeadm.stat.exists
