name: Deploy Kubernetes cluster

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      run_k8s_cluster:
        description: Enter "YES" to run k8s_cluster job
        required: true
        default: 'no'
      run_monitoring:
        description: Enter "YES" to run monitoring job
        required: true
        default: 'no'
      run_gha_arc:
        description: Enter "YES" to run gha_arc job
        required: true
        default: 'no'
      run_ycr_secret:
        description: Enter "YES" to run ycr_secret job
        required: true
        default: 'no'
      run_app:
        description: Enter "YES" to run app job
        required: true
        default: 'no'
  repository_dispatch:
    types: [ deploy-k8s ]

permissions:
  contents: read
  pull-requests: write

jobs:
  detect-changes:
    runs-on: ubuntu-24.04
    outputs:
      calico: ${{ steps.filter.outputs.calico }}
      gha-arc: ${{ steps.filter.outputs.gha-arc }}
      k8s: ${{ steps.filter.outputs.k8s }}
      monitoring: ${{ steps.filter.outputs.monitoring }}
      ycr: ${{ steps.filter.outputs.ycr }}

    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            calico:
              - 'roles/calico/**'
            gha-arc:
              - 'roles/gha_arc/**'
            k8s:
              - 'roles/k8s*/**'
              - 'roles/helm*/**'
              - 'roles/ingress_nginx*/**'
            monitoring:
              - 'roles/kube_prometheus/**'
            ycr:
              - 'roles/ycr_secret/**'

  k8s-cluster:
    name: Run k8s-cluster Ansible playbook
    needs: detect-changes
    if: |
      (github.event_name == 'workflow_dispatch' && github.event.inputs.run_k8s_cluster == 'YES') ||
      (github.event_name == 'pull_request' && needs.detect-changes.outputs.k8s == 'true')
    runs-on: ubuntu-24.04
    
    environment: code_review

    steps:
      - name: Clone repository on runner
        uses: actions/checkout@v6

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          log-public-key: false

      - name: Check required files
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ANSIBLE_INVENTORY_PATH: ${{ fromJSON(vars.ANSIBLE_INVENTORY).dir_path }}/${{ fromJSON(vars.ANSIBLE_INVENTORY).name }}
          YC_INFRA_BUCKET_NAME: ${{ fromJSON(vars.YC_INFRA_BUCKET).name }}
          TF_BACKEND_S3: ${{ vars.TF_BACKEND_S3 }}
        run: |
          set -euo pipefail

          check_file () {
            local key="$1"
            aws s3api head-object \
              --bucket "$YC_INFRA_BUCKET_NAME" \
              --key "$key" \
              --endpoint-url "$TF_BACKEND_S3" > /dev/null 2>&1 || \
              { echo "File $key not found. Run the Terraform yc-infra project."; exit 1; }
          }

          check_file "$ANSIBLE_INVENTORY_PATH"
          echo "The required files were found."

      - name: Download inventory file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ANSIBLE_INVENTORY_PATH: ${{ fromJSON(vars.ANSIBLE_INVENTORY).dir_path }}/${{ fromJSON(vars.ANSIBLE_INVENTORY).name }}
          YC_INFRA_BUCKET_NAME: ${{ fromJSON(vars.YC_INFRA_BUCKET).name }}
          TF_BACKEND_S3: ${{ vars.TF_BACKEND_S3 }}
        run: |
          aws s3 cp "s3://$YC_INFRA_BUCKET_NAME/$ANSIBLE_INVENTORY_PATH" \
            "$ANSIBLE_INVENTORY_PATH" --endpoint-url="$TF_BACKEND_S3"

      - name: Install Ansible requirements
        run: ansible-galaxy collection install -r requirements.yml

      - name: Run Ansible playbook
        env:
          ANSIBLE_INVENTORY_PATH: ${{ fromJSON(vars.ANSIBLE_INVENTORY).dir_path }}/${{ fromJSON(vars.ANSIBLE_INVENTORY).name }}
          K8S_VERSION: ${{ vars.K8S_VERSION }}
        run: ansible-playbook -i "$ANSIBLE_INVENTORY_PATH" k8s-cluster.yml

  monitoring:
    name: Run monitoring Ansible playbook
    needs: [ detect-changes, k8s-cluster ]
    if: |
      always() && needs.detect-changes.result == 'success' &&
      (needs.k8s-cluster.result == 'success' || needs.k8s-cluster.result == 'skipped') &&
      (
        (github.event_name == 'workflow_dispatch' && github.event.inputs.run_monitoring == 'YES') ||
        (github.event_name == 'pull_request' && needs.detect-changes.outputs.monitoring == 'true')
      )
    runs-on: ubuntu-24.04

    environment: code_review

    steps:
      - name: Clone repository on runner
        uses: actions/checkout@v6

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          log-public-key: false

      - name: Check required files
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ANSIBLE_INVENTORY_PATH: ${{ fromJSON(vars.ANSIBLE_INVENTORY).dir_path }}/${{ fromJSON(vars.ANSIBLE_INVENTORY).name }}
          YC_INFRA_BUCKET_NAME: ${{ fromJSON(vars.YC_INFRA_BUCKET).name }}
          TF_BACKEND_S3: ${{ vars.TF_BACKEND_S3 }}
        run: |
          set -euo pipefail

          check_file () {
            local key="$1"
            aws s3api head-object \
              --bucket "$YC_INFRA_BUCKET_NAME" \
              --key "$key" \
              --endpoint-url "$TF_BACKEND_S3" > /dev/null 2>&1 || \
              { echo "File $key not found. Run the Terraform yc-infra project."; exit 1; }
          }

          check_file "$ANSIBLE_INVENTORY_PATH"
          echo "The required files were found."

      - name: Download inventory file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ANSIBLE_INVENTORY_PATH: ${{ fromJSON(vars.ANSIBLE_INVENTORY).dir_path }}/${{ fromJSON(vars.ANSIBLE_INVENTORY).name }}
          YC_INFRA_BUCKET_NAME: ${{ fromJSON(vars.YC_INFRA_BUCKET).name }}
          TF_BACKEND_S3: ${{ vars.TF_BACKEND_S3 }}
        run: |
          aws s3 cp "s3://$YC_INFRA_BUCKET_NAME/$ANSIBLE_INVENTORY_PATH" \
            "$ANSIBLE_INVENTORY_PATH" --endpoint-url="$TF_BACKEND_S3"

      - name: Install Ansible requirements
        run: ansible-galaxy collection install -r requirements.yml

      - name: Run Ansible playbook
        env:
          ANSIBLE_INVENTORY_PATH: ${{ fromJSON(vars.ANSIBLE_INVENTORY).dir_path }}/${{ fromJSON(vars.ANSIBLE_INVENTORY).name }}
          K8S_VERSION: ${{ vars.K8S_VERSION }}
        run: ansible-playbook -i "$ANSIBLE_INVENTORY_PATH" monitoring.yml
  
  gha-arc:
    name: Run gha-arc Ansible playbook
    needs: [ detect-changes, k8s-cluster ]
    if: |
      always() && needs.detect-changes.result == 'success' &&
      (needs.k8s-cluster.result == 'success' || needs.k8s-cluster.result == 'skipped') &&
      (
        (github.event_name == 'workflow_dispatch' && github.event.inputs.run_gha_arc == 'YES') ||
        (github.event_name == 'pull_request' && needs.detect-changes.outputs.gha-arc == 'true')
      )
    runs-on: ubuntu-24.04

    steps:
      - name: Clone repository on runner
        uses: actions/checkout@v6

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          log-public-key: false

      - name: Generate token
        id: dip_app_vars_token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.SET_SECRET_APP_ID }}
          private-key: ${{ secrets.SET_SECRET_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: dip-app

      - name: Read variables from dip_app repo
        env:
          GH_TOKEN: ${{ steps.dip_app_vars_token.outputs.token }}
        run: |
          VAR_APP_NAMESPACE=$(gh variable get APP_NAMESPACE --repo "rizl-ad/dip-app")
          echo "APP_NAMESPACE=$VAR_APP_NAMESPACE" >> $GITHUB_ENV
      
      - name: Download inventory file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ANSIBLE_INVENTORY_PATH: ${{ fromJSON(vars.ANSIBLE_INVENTORY).dir_path }}/${{ fromJSON(vars.ANSIBLE_INVENTORY).name }}
          YC_INFRA_BUCKET_NAME: ${{ fromJSON(vars.YC_INFRA_BUCKET).name }}
          TF_BACKEND_S3: ${{ vars.TF_BACKEND_S3 }}
        run: |
          aws s3 cp "s3://$YC_INFRA_BUCKET_NAME/$ANSIBLE_INVENTORY_PATH" \
            "$ANSIBLE_INVENTORY_PATH" --endpoint-url="$TF_BACKEND_S3"

      - name: Install Ansible requirements
        run: ansible-galaxy collection install -r requirements.yml

      - name: Run Ansible playbook
        env:
          APP_ID: ${{ secrets.YC_K8S_ARC_APP_ID }}
          APP_INSTALLATION_ID: ${{ secrets.YC_K8S_ARC_APP_INSTALLATION_ID }}
          APP_PRIVATE_KEY: ${{ secrets.YC_K8S_ARC_APP_PRIVATE_KEY }}
          ANSIBLE_INVENTORY_PATH: ${{ fromJSON(vars.ANSIBLE_INVENTORY).dir_path }}/${{ fromJSON(vars.ANSIBLE_INVENTORY).name }}
          GITHUB_CONFIG_URL: "https://github.com/rizl-ad/dip-app"
          # ansible читает переменную APP_NAMESPACE
        run: ansible-playbook -i "$ANSIBLE_INVENTORY_PATH" gha-arc.yml
  
  ycr-secret:
    name: Run ycr-secret Ansible playbook
    needs: [ detect-changes, k8s-cluster ]
    if: |
      always() && needs.detect-changes.result == 'success' &&
      (needs.k8s-cluster.result == 'success' || needs.k8s-cluster.result == 'skipped') &&
      (
        (github.event_name == 'workflow_dispatch' && github.event.inputs.run_ycr_secret == 'YES') ||
        (github.event_name == 'pull_request' && needs.detect-changes.outputs.ycr == 'true')
      )
    runs-on: ubuntu-24.04

    steps:
      - name: Clone repository on runner
        uses: actions/checkout@v6

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          log-public-key: false
      
      - name: Generate token
        id: dip_app_vars_token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.SET_SECRET_APP_ID }}
          private-key: ${{ secrets.SET_SECRET_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: dip-app

      - name: Read variables from dip_app repo
        env:
          GH_TOKEN: ${{ steps.dip_app_vars_token.outputs.token }}
        run: |
          VAR_APP_NAMESPACE=$(gh variable get APP_NAMESPACE --repo "rizl-ad/dip-app")
          echo "APP_NAMESPACE=$VAR_APP_NAMESPACE" >> $GITHUB_ENV

      - name: Check required files
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          YC_INFRA_SA_KEY_FILE_PATH: ${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).name }}
          YC_INFRA_BUCKET_NAME: ${{ fromJSON(vars.YC_INFRA_BUCKET).name }}
          TF_BACKEND_S3: ${{ vars.TF_BACKEND_S3 }}
        run: |
          set -euo pipefail

          check_file () {
            local key="$1"
            aws s3api head-object \
              --bucket "$YC_INFRA_BUCKET_NAME" \
              --key "$key" \
              --endpoint-url "$TF_BACKEND_S3" > /dev/null 2>&1 || \
              { echo "File $key not found. Run the Terraform yc-prep project."; exit 1; }
          }

          check_file "$YC_INFRA_SA_KEY_FILE_PATH"
          echo "The required files were found."

      - name: Download inventory file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ANSIBLE_INVENTORY_PATH: ${{ fromJSON(vars.ANSIBLE_INVENTORY).dir_path }}/${{ fromJSON(vars.ANSIBLE_INVENTORY).name }}
          YC_INFRA_SA_KEY_FILE_PATH: ${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).name }}
          YC_INFRA_BUCKET_NAME: ${{ fromJSON(vars.YC_INFRA_BUCKET).name }}
          TF_BACKEND_S3: ${{ vars.TF_BACKEND_S3 }}
        run: |
          aws s3 cp "s3://$YC_INFRA_BUCKET_NAME/$ANSIBLE_INVENTORY_PATH" \
            "$ANSIBLE_INVENTORY_PATH" --endpoint-url="$TF_BACKEND_S3"
          aws s3 cp "s3://$YC_INFRA_BUCKET_NAME/$YC_INFRA_SA_KEY_FILE_PATH" \
            "$YC_INFRA_SA_KEY_FILE_PATH" --endpoint-url="$TF_BACKEND_S3"

      - name: Install Ansible requirements
        run: ansible-galaxy collection install -r requirements.yml

      - name: Run Ansible playbook
        env:
          ANSIBLE_INVENTORY_PATH: ${{ fromJSON(vars.ANSIBLE_INVENTORY).dir_path }}/${{ fromJSON(vars.ANSIBLE_INVENTORY).name }}
          YC_INFRA_SA_KEY_FILE_PATH: ${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).name }}
          # ansible читает переменную APP_NAMESPACE
        run: ansible-playbook -i "$ANSIBLE_INVENTORY_PATH" ycr-secret.yml

  app:
    name: Deploy app
    needs: [ gha-arc, ycr-secret ]
    if: |
      !cancelled() && !failure() &&
      needs.detect-changes.result == 'success' &&
      (needs.k8s-cluster.result == 'success' || needs.k8s-cluster.result == 'skipped') &&
      (needs.gha-arc.result == 'success' || needs.gha-arc.result == 'skipped') &&
      (needs.ycr-secret.result == 'success' || needs.ycr-secret.result == 'skipped') &&
      (
        (github.event_name == 'workflow_dispatch' && github.event.inputs.run_app == 'YES') ||
        (
          github.event_name == 'pull_request' &&
          (needs.detect-changes.outputs.gha-arc == 'true' || needs.detect-changes.outputs.ycr == 'true')
        )
      )
    runs-on: ubuntu-24.04

    steps:
      - name: Generate token
        id: wf_call_token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.REMOTE_WORKFLOW_CALL_APP_ID }}
          private-key: ${{ secrets.REMOTE_WORKFLOW_CALL_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: dip-app

      - name: Remote workflow call
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ steps.wf_call_token.outputs.token }}
          repository: rizl-ad/dip-app
          event-type: deploy-app