name: Deploy Kubernetes cluster

on:
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [ deploy-k8s ]

permissions:
  contents: read
  pull-requests: write

jobs:

  ansible-playbook:
    name: Run Ansible playbook
    runs-on: ubuntu-24.04

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      YC_BUCKET: ${{ vars.YC_BUCKET }}
      ANSIBLE_SSH_ARGS: "-o ControlMaster=no -o ControlPersist=no"

    steps:
      - name: Clone repository on runner
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # - name: Check required files
      #   run: |
      #     set -euo pipefail

      #     check_file () {
      #       local key="$1"
      #       aws s3api head-object \
      #         --bucket "${{ github.event.client_payload.bucket }}" \
      #         --key "$key" \
      #         --endpoint-url "${{ github.event.client_payload.endpoint }}" > /dev/null 2>&1 || \
      #         { echo "File $key not found. Run the Terraform yc-infra project."; exit 1; }
      #     }

      #     check_file "${{ github.event.client_payload.key }}"
      #     echo "The required files were found."

      - name: Check required files
        run: |
          set -euo pipefail

          check_file () {
            local key="$1"
            aws s3api head-object \
              --bucket "${{ fromJSON(vars.YC_BUCKET).bucket }}" \
              --key "$key" \
              --endpoint-url "${{ fromJSON(vars.YC_BUCKET).endpoint }}" > /dev/null 2>&1 || \
              { echo "File $key not found. Run the Terraform yc-infra project."; exit 1; }
          }

          check_file "${{ fromJSON(vars.YC_BUCKET).key }}"
          echo "The required files were found."

      # - name: Download inventory file
      #   run: |
      #     aws s3 cp "s3://${{ github.event.client_payload.bucket }}/${{ github.event.client_payload.key }}" \
      #       "${{ github.event.client_payload.key }}" --endpoint-url="${{ github.event.client_payload.endpoint }}"

      - name: Download inventory file
        run: |
          aws s3 cp "s3://${{ fromJSON(vars.YC_BUCKET).bucket }}/${{ fromJSON(vars.YC_BUCKET).key }}" \
            "${{ fromJSON(vars.YC_BUCKET).key }}" --endpoint-url="${{ fromJSON(vars.YC_BUCKET).endpoint }}"

      - name: Install Ansible requirements
        run: ansible-galaxy collection install -r requirements.yml

      # - name: Show Ansible version
      #   run: ansible --version

      # - name: Show Ansible config
      #   run: ansible-config dump

      # - name: Show files list
      #   run: ls -lha

      # - name: Ansible host key checking off
      #   run: export ANSIBLE_HOST_KEY_CHECKING=False

      # - name: Create control socket directory
      #   run: mkdir -p /home/runner/.ansible/cp

      - name: Run Ansible playbook
        run: ansible-playbook -i "${{ github.event.client_payload.key }}" main.yml -vvvv
        
